version: '2'

services:
  db:
    container_name: blog_db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d

  gems:
    container_name: blog_gems
    image: busybox
    volumes:
      - /ruby_gems

  web:
    container_name: blog_web
    build: .
    depends_on:
      - db
      - gems
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    volumes_from:
      - gems
    tty: true
    stdin_open: true
