model:
  post:
    title_min_length: 10
    title_max_length: 255
    content_min_length: 10
    content_max_length: 10000
    per_page: 10

  comment:
    content_max_length: 5000
    content_min_length: 5
    per_page: 10
